In [2]:
import torch

In [2]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

In [9]:
kernel = torch.Tensor(1,1,3,3)
kernel[0, 0] = torch.tensor([[0., 0., 0.], [0., 0., 0.], [0., 0., 1.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, bias=False)

In [10]:
trans.weight = torch.nn.Parameter(kernel)

In [11]:
trans(img)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 1., 2.],
          [0., 0., 3., 4.]]]], grad_fn=<ConvTranspose2DBackward>)

In [3]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[1., 0.], [0., 0.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=2, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[1., 0., 2., 0.],
          [0., 0., 0., 0.],
          [3., 0., 4., 0.],
          [0., 0., 0., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [2]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[1., 0.], [0., 0.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[1., 2., 0.],
          [3., 4., 0.],
          [0., 0., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [3]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[0., 1.], [0., 0.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 1., 2.],
          [0., 3., 4.],
          [0., 0., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [4]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[0., 0.], [1., 0.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 0., 0.],
          [1., 2., 0.],
          [3., 4., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [5]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[0., 0.], [0., 1.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 0., 0.],
          [0., 1., 2.],
          [0., 3., 4.]]]], grad_fn=<ConvTranspose2DBackward>)

In [6]:
img = torch.Tensor(1,1,2,2)
img[0, 0] = torch.tensor([[1, 2], [3, 4]]).float()

kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[1., 1.], [0., 0.]]).float()

trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[1., 3., 2.],
          [3., 7., 4.],
          [0., 0., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [22]:
kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[0., 1.], [1., 0.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 1., 2.],
          [1., 5., 4.],
          [3., 4., 0.]]]], grad_fn=<ConvTranspose2DBackward>)

In [23]:
kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[0., 0.], [1., 1.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 0., 0.],
          [1., 3., 2.],
          [3., 7., 4.]]]], grad_fn=<ConvTranspose2DBackward>)

In [24]:
kernel = torch.Tensor(1,1,2,2)
kernel[0, 0] = torch.tensor([[1., 0.], [0., 1.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[1., 2., 0.],
          [3., 5., 2.],
          [0., 3., 4.]]]], grad_fn=<ConvTranspose2DBackward>)

In [25]:
kernel = torch.Tensor(1,1,3,3)
kernel[0, 0] = torch.tensor([[0., 0., 0.], [0., 0., 0.], [0., 0., 1.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 1., 2.],
          [0., 0., 3., 4.]]]], grad_fn=<ConvTranspose2DBackward>)

In [26]:
kernel = torch.Tensor(1,1,3,3)
kernel[0, 0] = torch.tensor([[0., 0., 0.], [0., 1., 0.], [0., 0., 0.]]).float()
trans = torch.nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, bias=False)
trans.weight = torch.nn.Parameter(kernel)
trans(img)

tensor([[[[0., 0., 0., 0.],
          [0., 1., 2., 0.],
          [0., 3., 4., 0.],
          [0., 0., 0., 0.]]]], grad_fn=<ConvTranspose2DBackward>)